Redirect PortgreSQL tools check output to stderr

diff --git a/commands b/commands
--- a/commands
+++ b/commands
@@ -33,7 +33,7 @@ function check_postgresql_container() {
 function check_postgresql_tool() {
     local tool_name="$1"
     if [[ $(whereis $tool_name | awk '{ print NF }') -eq 1 ]]; then
-        echo "'${tool_name}' not found. Is the package 'postgresql-client' installed?"
+        echo "'${tool_name}' not found. Is the package 'postgresql-client' installed?" 1>&2
         exit 1
     fi
 }
